name: Robust Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # --- Configuration ---
            # The absolute path to your project directory on the server.
            # !! IMPORTANT: Change this if your username is not 'ubuntu24' !!
            PROJECT_DIR="/home/ubuntu24/my-api"
            
            # The repository URL is automatically constructed from GitHub context.
            REPO_URL="https://github.com/${{ github.repository }}.git"
            
            # --- Automation Script Starts ---
            echo ">>> Starting deployment process..."
            
            # Step 1: Check for project directory and clone or pull accordingly.
            if [ -d "$PROJECT_DIR" ]; then
              echo ">>> Project directory exists. Pulling latest changes..."
              cd "$PROJECT_DIR"
              git pull
            else
              echo ">>> Project directory not found. Cloning repository..."
              git clone "$REPO_URL" "$PROJECT_DIR"
              cd "$PROJECT_DIR"
            fi
            
            echo ">>> Successfully changed directory to: $(pwd)"

            # Step 2: Check for the virtual environment and create it if it doesn't exist.
            if [ ! -d "venv" ]; then
              echo ">>> Virtual environment not found. Creating a new one..."
              python3 -m venv venv
            fi
            
            # Step 3: Activate venv and install dependencies.
            echo ">>> Activating virtual environment..."
            source venv/bin/activate
            
            # FIX: Force install a compatible version of Werkzeug before other requirements.
            # This fixes the "ImportError: cannot import name 'url_quote'".
            # Flask 2.2.2 is not compatible with Werkzeug >= 3.0.
            echo ">>> Installing compatible Werkzeug version to fix dependency issue..."
            pip install "Werkzeug<3.0"
            
            echo ">>> Installing requirements from requirements.txt..."
            pip install -r requirements.txt
            
            # Step 4: Ensure tmux is installed.
            if ! command -v tmux &> /dev/null; then
                echo ">>> tmux not found. Installing it..."
                sudo apt-get update
                sudo apt-get install -y tmux
            fi
            
            # Step 5: Start or restart the application using tmux and log its output.
            echo ">>> Restarting the application within a tmux session..."
            tmux kill-session -t my-api || true
            
            # NEW: Redirect all output (stdout and stderr) from the app to app.log.
            # This is the key to debugging silent failures.
            tmux new-session -d -s my-api "venv/bin/python app.py > app.log 2>&1"
            
            sleep 3 # Give the app a moment to start up or crash.
            
            # Step 6: Verify and debug.
            echo ">>> Verifying tmux session status:"
            tmux ls

            echo ">>> Displaying the last 20 lines of the application log for debugging:"
            # NEW: We print the log file. If the app crashed, the error will be shown here.
            cat app.log
            
            echo ">>> Deployment finished."

