name: Robust Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # --- Configuration ---
            # The absolute path to your project directory on the server.
            # !! IMPORTANT: Change this if your username is not 'ubuntu24' !!
            PROJECT_DIR="/home/ubuntu24/my-api"
            
            # The repository URL is automatically constructed from GitHub context.
            REPO_URL="https://github.com/${{ github.repository }}.git"
            
            # --- Automation Script Starts ---
            echo ">>> Starting deployment process..."
            
            # Step 1: Check for project directory and clone or pull accordingly.
            # If the project directory already exists, navigate into it and pull the latest changes.
            if [ -d "$PROJECT_DIR" ]; then
              echo ">>> Project directory exists. Pulling latest changes..."
              cd "$PROJECT_DIR"
              git pull
            # If the project directory does not exist, clone the repository from GitHub.
            else
              echo ">>> Project directory not found. Cloning repository..."
              git clone "$REPO_URL" "$PROJECT_DIR"
              cd "$PROJECT_DIR"
            fi
            
            echo ">>> Successfully changed directory to: $(pwd)"

            # Step 2: Check for the virtual environment and create it if it doesn't exist.
            if [ ! -d "venv" ]; then
              echo ">>> Virtual environment not found. Creating a new one..."
              python3 -m venv venv
            fi
            
            # Step 3: Activate the virtual environment and install dependencies.
            echo ">>> Activating virtual environment and installing requirements..."
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Step 4: Restart the application.
            echo ">>> Restarting the application..."
            # Find and kill the old running process. '|| true' prevents the script from failing if the process doesn't exist.
            pkill -f 'venv/bin/python app.py' || true
            # Start the new application in the background using nohup.
            # Redirect stdout and stderr to a log file.
            nohup venv/bin/python app.py > app.log 2>&1 &
            
            echo ">>> Deployment finished successfully!"

