name: Simple Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # به پوشه پروژه بروید
            cd /home/user/my-api
            
            # آخرین تغییرات را بگیرید
            git pull
            
            # محیط مجازی را فعال کنید (بسیار مهم)
            source venv/bin/activate
            
            # نیازمندی‌ها را نصب کنید
            pip install -r requirements.txt
            
            # پروسه قبلی را متوقف کنید
            pkill -f 'venv/bin/python app.py' || true
            
            # برنامه را با پایتونِ محیط مجازی اجرا کنید (بسیار مهم)
            nohup venv/bin/python app.py &
